### ISSUE TITLE
It's a rhombus not a diamond please can the name be changed.

### ISSUE THREAD

**Issue by MaidofSteel** [bbcmicrobit/micropython#110]

**Comment by deshipu** [comment]
What are you talking about?

**Comment by markshannon** [comment]
To quote https://www.mathsisfun.com/geometry/rhombus.html "A rhombus looks like a diamond" :smile: 
While "rhombus" may be more technically correct, "diamond" is more widely known.
We should keep "diamond"

**Comment by deshipu** [comment]
I thought those are card colors. Clubs, Diamonds, Hearts and Spades?

**Comment by deshipu** [comment]
Should we add Clubs and Spades?

**Comment by markshannon** [comment]
Trouble is, the display doesn't do black, only red.

**Comment by deshipu** [comment]
You can do negative?

**Comment by markshannon** [comment]
It looks like we are sticking with diamond.
