### ISSUE TITLE
Add SPI?

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#12]
The device supports SPI but it's not in the DAL.

**Comment by ntoll** [comment]
Could this be part of the device2device work for 1.1?

**Comment by dpgeorge** [comment]
It could but I don't think it's optimal.  SPI requires 3 lines + GND which is a lot to wire up compared with, eg, 1-wire or even I2C or UART.

**Comment by ntoll** [comment]
Given this is sub-optimal and requires fiddly wiring up, I'll bump this from 1.1.

**Comment by carlosperate** [comment]
Is this currently a matter of having to wait for the SPI to be added to the DAL?

**Comment by dpgeorge** [comment]
Now added.
