### ISSUE TITLE
Weird behavior of struct.pack

### ISSUE THREAD

**Issue by deshipu** [bbcmicrobit/micropython#126]
So once I got I2C working, I started to make use of struct.pack to send the right bytes, and I stumbled upon this:

```
>>> import struct
>>> struct.pack("f", 0.1)
b'\xcc\xcc\xcc='
>>> struct.pack("<f", 0.1)
b'\xcc\xcc\xcc='
>>> struct.pack("<ccf", 0, 4, 0.1)
b'\xcc\xcc\xcc='
>>> struct.pack("<c", 0)          
b''
>>> struct.pack("<c", b'\xff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert bytes to int
```

Comparing it to cPython3:
```
>>> import struct
>>> struct.pack("<c", 0xff)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: char format requires a bytes object of length 1
>>> struct.pack("<c", b'\xff')
b'\xff'
```

**Comment by dpgeorge** [comment]
The 'c' code is not implemented.  Use 'B' instead (and then the arg should be an integer, so use ord(bytes) if needed).

**Comment by deshipu** [comment]
ok, one more weirdness:
```
>>> sp(f0.t.pack("b<f", 0, 0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert float to int
>>> struct.pack("b<f", 0, 0xff, 0.1)
b'\x00\x00\x00\x00\xcc\xcc\xcc='
```

**Comment by deshipu** [comment]
(I know that "b<f" is invalid, but still)

**Comment by dpgeorge** [comment]
If you give it a valid format string (excl using 'c') then it'll work.  And it's not crashing when the format string is invalid, so that's good enough.

If you want to make all these corner cases given decent error messages then MicroPython grows 2x in size and no longer works on microbit :(

**Comment by deshipu** [comment]
Understood.
