### ISSUE TITLE
Building old version?

### ISSUE THREAD

**Issue by jrmhaig** [bbcmicrobit/micropython#127]
I have recently rebuilt and when I upload it appears to result in an old version. Specifically, the help documentation does not have the 'Stuff to explore' section and I have found that the 'music' functions are missing.

I have checked out revision 0189136af557bc2c8514935f7351bcaafe32c47f (Allow music tunes to be played in the background) as this was the actual update I am interested in and this is working correctly for me.

**Comment by ntoll** [comment]
@jrmhaig all of these changes should be in master. Just pulling latest master should fix it. :-)

**Comment by dpgeorge** [comment]
Music is now a separate module and you need to do `import music`.

**Comment by jrmhaig** [comment]
OK, it was music going into a separate module that confused me. Sorry.
