### ISSUE TITLE
write_analog doesn't accept a float

### ISSUE THREAD

**Issue by tomviner** [bbcmicrobit/micropython#137]
The [docs say](https://microbit-micropython.readthedocs.org/en/latest/pin.html#microbit.MicroBitAnalogDigitalPin.write_analog):
> write_analog(value)
> Output a PWM signal on the pin, with the duty cycle proportional to the provided value. The value may be either an integer or a floating point number between 0 (0% duty cycle) and 1023 (100% duty).

But:
```python
>>> microbit.pin0.write_analog(0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert float to int
```

Also just to really confuse things:
```python
>>> help(microbit.pin0.write_analog)
micro:bit, write_analog(value) to the pin. You can use a whole number between
0 and 255 as the value.
```

Let's decide if floats should be allowed or not (I'd say *why not?*), and fix either the docs (which I can do a patch for) or the implementation.

**Comment by carlosperate** [comment]
I also believe it should accept floating point, as a lot of people will input the result of a mathematical operation. Of course, the peripheral requires an integer, but that is a conversion that should be done inside the micropython function,

**Comment by dpgeorge** [comment]
Analog output is in principle a "continuous" quantity, so I'd say it should accept a float.

**Comment by tomviner** [comment]
Docs fix: https://github.com/bbcmicrobit/micropython/pull/138

I'll leave getting floats working for someone with better c++ knowledge.
