### ISSUE TITLE
Can't import music

### ISSUE THREAD

**Issue by MarcScott** [bbcmicrobit/micropython#149]
Running mu on a Raspberry Pi
When trying:
 `from microbit import music`
results is:
`ImportError: cannot import name music`

**Comment by ntoll** [comment]
We've move the music module out of `microbit`. Just use `import music`. We know we need to update the documentation. ;-)

**Comment by ntoll** [comment]
BTW... I've created a microbit channel on Freenode - I'm the only one in it at the moment, if you want instant answers, that's the place to be. ;-)
