### ISSUE TITLE
Should be able to ctrl-C to stop an ongoing display animation

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#175]
Currently if you do:
```python
>>> display.scroll('microbit')
```
then you can't use ctrl-C to stop it.  This should be fixed!

**Comment by ntoll** [comment]
I'd say yes.... @markshannon ..?

(Or no, if it's an inordinate amount of work given time constraints).

**Comment by dpgeorge** [comment]
It's pretty easy to do.  Just follow the pattern from the music module.

**Comment by ntoll** [comment]
then a definite yes. I'll be reviewing any/all outstanding PRs this evening... ;-)
