### ISSUE TITLE
String.format() right justification not working for string arguments

### ISSUE THREAD

**Issue by realcundo** [bbcmicrobit/micropython#182]
When playing with Marja (using [`firmware.hex`](https://github.com/ntoll/microrepl/blob/master/firmware.hex)) I came across this:
```python
print("x{:>4}x".format(42))
print("x{:>4}x".format("42")
```
produced
```
x  42x
x42  x
```
Not a big deal but I was wondering whether this was intentional, consequence of squeezing as much Python into as little space as possible (justification is ignored?), or a genuine bug.

**Comment by dpgeorge** [comment]
This is now fixed in the upstream code.  I'll see if I have time to sneak those fixes into microbit before v1.0....

**Comment by ntoll** [comment]
Yes please :-)

**Comment by dpgeorge** [comment]
Actually, this is already fixed.  You must have an older version of the firmware.
