### ISSUE TITLE
No LICENSE file?

### ISSUE THREAD

**Issue by gbaman** [bbcmicrobit/micropython#193]
I just noticed, the MicroPython repository has no LICENSE file. Without it, the appropriate license has to be specified in each file. Which in nearly all (if not all) the code files, it has been done (with MIT). But that doesn't cover stuff like /tools, /docs (what I was interested in) or /examples so technically, they are covered under "No License", meaning in general ["nobody else may reproduce, distribute, or create derivative works"](http://choosealicense.com/no-license/) from these sections.

Is there any reason a LICENSE file hasn't been added? Am I missing something?

**Comment by ntoll** [comment]
Good spot. We should add one.

**Comment by zitterbewegung** [comment]
If we are adding a license do we have to contact everyone that contributed
code for consent to release it under a license? I don't remember that there
is a contributor agreement either .

**Comment by JoeGlancy** [comment]
What about examples? Quite a few of them have no licensed or terms attached. Perhaps public domain would be ideal for examples? But then the respective authors would need to be contacted.

**Comment by dpgeorge** [comment]
I think that, for the C/C++ code at least, it was implicit that it's under the original license of MicroPython, ie MIT.  But I agree we need to add a LICENSE file and make sure people are happy with it.

**Comment by dpgeorge** [comment]
Dear all contributors to this repository: @dpgeorge @ntoll @markshannon @deshipu @matthewelse @willingc @tomviner @alanmjackson @funkyHat @paulegan @jrmhaig @alexwlchan @ncoghlan @gbaman @kwadrat @JoeGlancy 

Are you ok with your code being licensed under the MIT license?  If you're not familiar with this license, see the links below (it's very easy to understand, compared with licenses in general).

https://opensource.org/licenses/MIT
https://en.wikipedia.org/wiki/MIT_License

Thanks!

**Comment by ntoll** [comment]
Completely happy.

I presume that if code is explicitly licensed as something else this will remain in place (the only code I can think of are some examples Larry and I wrote and donated to the public domain).

**Comment by jrmhaig** [comment]
Yes, I'm happy with this.

**Comment by dpgeorge** [comment]
> I presume that if code is explicitly licensed as something else this will remain in place

Yes, individual files can be licensed differently to the overall license.

**Comment by JoeGlancy** [comment]
Go for it

**Comment by gbaman** [comment]
Yip, I am happy with it.

**Comment by deshipu** [comment]
I agree

**Comment by kwadrat** [comment]
Yes, I am OK with my code being licensed under the MIT license.

**Comment by ncoghlan** [comment]
Good catch, and yes, I am fine with my contributions being published under the MIT license.

**Comment by markshannon** [comment]
Yes, for all the code I have contributed so far.

For all l future contributions: yes, unless I explicitly state otherwise.

**Comment by funkyHat** [comment]
Yes I'm happy with MIT :)

**Comment by alexwlchan** [comment]
MIT license is fine for me. :-)

**Comment by Neon22** [comment]
yes. MIT 
    mine are labelled public domain - should we edit ?
    
    On 2/9/2016 11:37 PM, Damien George
      wrote:
    
    
      Dear all contributors to this repository: @dpgeorge @ntoll
        @markshannon @deshipu @matthewelse
        @willingc @tomviner
        @alanmjackson @funkyHat @paulegan
        @jrmhaig @alexwlchan
        @nco ghlan @gbaman @kwadrat
        @JoeGlancy 
      Are you ok with your code being licensed under the MIT license?
        If you're not familiar with this license, see the links below
        (it's very easy to understand, compared with licenses in
        general).
      https://opensource.org/licenses/MIT
        https://en.wikipedia.org/wiki/MIT_License
      Thanks!
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      No virus
        found in this message.
        Checked by AVG - www.avg.com
        Version: 2016.0.7357 / Virus Database: 4522/11587 - Release
        Date: 02/08/16

**Comment by dpgeorge** [comment]
@Neon22 if it's already public domain, no problem.

**Comment by willingc** [comment]
Yes, I am fine with MIT :-)

**Comment by tomviner** [comment]
I approve this message. Happy with MIT.

**Comment by ntoll** [comment]
@tomviner https://www.youtube.com/watch?v=rCcqMzuezaI ;-)

**Comment by zitterbewegung** [comment]
I have no issue with this.

**Comment by dpgeorge** [comment]
Ok, just waiting on responses from: @matthewelse @alanmjackson @paulegan

**Comment by paulegan** [comment]
Yes to MIT

**Comment by matthewelse** [comment]
MIT's fine with me!

**Comment by dpgeorge** [comment]
Addressed by #229.
