### ISSUE TITLE
Linux installation instruction refer to out of date ppa.

### ISSUE THREAD

**Issue by mjs-arm** [bbcmicrobit/micropython#203]
The installation guide for linux refers to ppa:terry.guo/gcc-arm-embedded. This PPA is no longer maintained, it has been replaced by ppa:team-gcc-arm-embedded

There was an announcement about this change from Thomas in the GNU R/M toolchain team here: 
https://launchpad.net/gcc-arm-embedded/+announcement/13824

**Comment by microbit-carlos** [comment]
Thanks @mjs-arm, this was fixed in https://github.com/bbcmicrobit/micropython/pull/294.
