### ISSUE TITLE
Simple radio module?

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#210]
See ble-services/MicroBitRadio.cpp in the DAL.

**Comment by JoeGlancy** [comment]
`source/ble-services/MicroBitRadioDatagram.cpp` might be more suited to this, would it not?

**Comment by finneyj** [comment]
Folks - please be aware that the BBC child protection team are currently reviewing this low level radio API to ensure were not putting kids at any risk here (I know, but these guys want to ensure there are no privacy concerns etc), and have requested that all languages refrain from making any public APIs visible until the review is complete...

**Comment by zeth** [comment]
There is a nice API now visible here: 
https://github.com/Microsoft/yelm/blob/master/libs/microbit-radio/radio.ts

So can we assume from that the review finished?

**Comment by zeth** [comment]
Ignore last, it is answered here:
https://github.com/bbcmicrobit/micropython/issues/71

**Comment by markshannon** [comment]
We have a radio module now.
