### ISSUE TITLE
OpenSSL dependancy needs adding to doc

### ISSUE THREAD

**Issue by WayneKeenan** [bbcmicrobit/micropython#230]
On Ubuntu Trusty I received this error whilst installing Yotta

`build/temp.linux-x86_64-3.4/_openssl.c:431:25: fatal error: openssl/aes.h: No such file or directory`

It was necessary to run the following before installing Yotta 

`sudo apt-get install libssl-dev`

**Comment by JoeGlancy** [comment]
Strange, I never got an error like that, and my system was completely clean
(VM).

**Comment by dpgeorge** [comment]
It could be that yotta was recently upgraded and now relies on libssl.  Can anyone else confirm this?

**Comment by komeP** [comment]
yotta depends on cryptography now, which depends on the OpenSSL headers.

**Comment by carlosperate** [comment]
Last time I had to install yotta over a month or two ago it already needed libssl-dev.

**Comment by carlosperate** [comment]
@dpgeorge  or @ntoll, this is already in the README, so this issue can be closed.
