### ISSUE TITLE
r.e. docs: isn't importing * a bad practice to encourage?

### ISSUE THREAD

**Issue by paddywwoof** [bbcmicrobit/micropython#234]
Especially if the target audience are not experienced programmers... it will be unclear where 'display' has come from. I think there are several PEPs on this subject.

**Comment by dpgeorge** [comment]
There was a long discussion about this on the mailing list (sorry, no reference!).  The microbit is supposed to have a barrier to entry which is as low as possible, and having to type "import microbit" then "microbit.display" etc was deemed "one new concept too much" when teaching the basics to children.

**Comment by markshannon** [comment]
@paddywwoof Any objection to closing this issue?

**Comment by paddywwoof** [comment]
No. And thanks for all the work you've (collectively) put in.
