### ISSUE TITLE
error can't locate "lancaster-university/microbit-dal"

### ISSUE THREAD

**Issue by vlee489** [bbcmicrobit/micropython#235]
Having a small problem of accessing lancaster-university/microbit-dal

    error: Failed to satisfy dependencies of C:\Users\Vincent\Documents\MicroBit\micropython - built:
    error: could not locate github component "lancaster-university/microbit-dal", either the name is     misspelt, you do not have access to it, or it does not exist

Is it a private repo on github?

**Comment by JoeGlancy** [comment]
Currently yes, I believe it is. It might be going open source soon, I'm not
sure. But right now it's a private repo - Nick or Damian know more though,
and can comment on availability. Hopefully it'll be open-sourced soon :)

**Comment by vlee489** [comment]
Closed
