### ISSUE TITLE
Display.Input ()

### ISSUE THREAD

**Issue by damianburrin** [bbcmicrobit/micropython#248]
Both the touch developer and the block editor have a light level feature that reads the exterior light level via the leds.

Could this be added to the MicroPython version?

**Comment by markshannon** [comment]
Does it work?

**Comment by damianburrin** [comment]
It does in the touch and blocks version but doesn't seem to be supported in the python tool set

**Comment by markshannon** [comment]
Sorry, I wasn't clear there. 
Does it provide reliable readings of the external light level?

**Comment by damianburrin** [comment]
Yes in the block and touch it gives a value from 0 to 255 ( so i guess theres an 8bit adc somewhere)  as you flash a light on the leds (un lit) thee value rises which can be read via a block or touch code.  ive done a cpl of mini programs using them one displays a 'graph' based on how much light is being recieved the other is a theramin that increases the pitch of a tone based on light.

Works well but would prefer to do it in python with the students.

Damian

**Comment by damianburrin** [comment]
Yes in the block and touch it gives a value from 0 to 255 ( so i guess theres an 8bit adc somewhere)  as you flash a light on the leds (un lit) thee value rises which can be read via a block or touch code.  ive done a cpl of mini programs using them one displays a 'graph' based on how much light is being recieved the other is a theramin that increases the pitch of a tone based on light.
Works well but would prefer to do it in python with the students.
Damian
On 29 Mar 2016 19:53, Mark Shannon <notifications@github.com> wrote:Sorry, I wasn't clear there. 
Does it provide reliable readings of the external light level?

**Comment by markshannon** [comment]
OK, thanks.

**Comment by bjost2s** [comment]
I am also looking for the light level function, is it already implemented?

**Comment by ZanderBrown** [comment]
Any progress on this?
Obviously it wouldn't be especially accurate but would be good to have.

**Comment by microbit-carlos** [comment]
`display.read_light_level()` method was added in https://github.com/bbcmicrobit/micropython/commit/02ef4d03bef9a72f60bb7f0f2ae1b90c75cd9432 and included in MicroPython v1.0.0.
