### ISSUE TITLE
f.write

### ISSUE THREAD

**Issue by damianburrin** [bbcmicrobit/micropython#261]
Is it possible to include the f.wrirte library to be able to write data say from the acceleromter to the on board flash storage?

Thank you

**Comment by dpgeorge** [comment]
This (a filesystem) will be implemented soon.

**Comment by ntoll** [comment]
See the great work from @markshannon in #251 :-)

**Comment by damianburrin** [comment]
Thanks chaps - I'm new to git hub and have just found the file system section from @markshannon looking forward to it being included (it's not in the online version as yet)

**Comment by markshannon** [comment]
#251 has been merged now.
