### ISSUE TITLE
Add display.disable() and display.enable()

### ISSUE THREAD

**Issue by markshannon** [bbcmicrobit/micropython#274]

**Comment by carlosperate** [comment]
This could also be useful to enable touch support for those pins thanks to https://github.com/lancaster-university/microbit-dal/issues/90 
(would it have to get backported to 1.4.x? @finneyj offered to do that, but I am not quite sure what is the plan with updating the DAL version for micropython)

**Comment by dpgeorge** [comment]
Might also be nice to be able to query the current state of the display, eg is_enabled().  But to avoid adding 3 very simple methods (disable, enable, is_enabled) how about a single method like display.active():
```
if display.active():
    print('it's active!')

display.active(True) # enable it
display.active(False) # disable it
```

> but I am not quite sure what is the plan with updating the DAL version for micropython

We need to decide on this.

**Comment by markshannon** [comment]
After much discussion (at the PyCon sprints), we've decided that three functions are clearer than one.
`on()`, `off()`, and `is_active()` is the current favourite trio.
@dpgeorge Any compelling reason not to have three functions?

**Comment by ntoll** [comment]
We should also use the same convention with the `radio` module since that's another thing that can be turned on and off.

**Comment by dpgeorge** [comment]
> Any compelling reason not to have three functions?

Having only 1 method saves code size (don't need 3 interned strings, or 3 Python wrappers for the separate functions).  But if you had a long discussion and think that 3 are clearer then go for it!

But can you think of something even simpler for is_active(), eg is_on()?

**Comment by ntoll** [comment]
+1 `is_on`
