### ISSUE TITLE
Incorrect error message on ImportError

### ISSUE THREAD

**Issue by lordmauve** [bbcmicrobit/micropython#290]
The error message when importing a submodule that does not exist, incorrectly states that the containing package does not exist.

```
>>> import microbit
>>> microbit
<module 'microbit'>
>>> import microbit.lemon.jelly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'microbit'
```

**Comment by dpgeorge** [comment]
This is a bug to discuss upstream at https://github.com/micropython/micropython

**Comment by markshannon** [comment]
I've reported this upstream as https://github.com/micropython/micropython/issues/2609
