### ISSUE TITLE
running_time() is always divisible by 6

### ISSUE THREAD

**Issue by matt-land** [bbcmicrobit/micropython#291]
The running_time() is always divisible by six after the first second of run time.

In the repl console, we ran this code, and got zeros:
from microbit import *
while True:
    print(running_time() % 6)

This seems odd. Shouldn't it vary?

**Comment by dpgeorge** [comment]
It's because the granularity of the ticker is 6ms.  See MILLISECONDS_PER_MACRO_TICK in inc/lib/ticker.h.

**Comment by matt-land** [comment]
ok thanks
