### ISSUE TITLE
import radio -  No Module named 'radio'

### ISSUE THREAD

**Issue by systemparanoia** [bbcmicrobit/micropython#330]
Hi

I hve just got a new microbit.
I have attempted the firefly example
I am using MU and I am unable to import the radio function.
I am unable to see it listed in the repl with dir()

Am i doing something wrong or are the docs wrong?

**Comment by ntoll** [comment]
You need the latest version of Mu, available from here:

http://codewith.mu/

Hope this helps,

N.

**Comment by systemparanoia** [comment]
That was it. Thanks
