### ISSUE TITLE
Using music.play after speech.say results in no sound or garbled sound

### ISSUE THREAD

**Issue by iansparks** [bbcmicrobit/micropython#335]
Using the mu editor for python / microbit. It reports: MicroPython v1.7-9-gbe020eb

The following program:

``` python
from microbit import *
import music
import speech
music.play(music.WAWAWAWAA, wait=True)
speech.say('Hello world')
sleep(2000)
music.play(music.WAWAWAWAA, wait=True)
```

Does not play the second WAWAWA... tune (with speaker attached to GND + PIN0). Remove speech.say() and it works as expected. Seems that speech.say leaves the microbit sound system in some altered state? I have tried music.reset() but does not seem to help.

**Comment by dpgeorge** [comment]
The implementation of the music module was done first using simple PWM output.  Speech was added later uses the new audio module which can handle more sophisticated sounds and uses a more direct (low-level) way of outputing the data to the GPIO pin.  These 2 methods are not compatible.  Probably music should be updated to work alongside the newer audio functionality.

**Comment by deshipu** [comment]
Alternatively speech should be updated to clean up after itself properly.

**Comment by markshannon** [comment]
@deshipu Could you be more specific? What state should be restored?

**Comment by deshipu** [comment]
I really don't know the specifics of how this works. All I know is that pin.write_analog() doesn't work after using speech/music on it, as we discovered recently on Europython with @ntoll.

**Comment by markshannon** [comment]
`pin.write_analog()` uses the new PWM and is unrelated to`music.play()` which uses the old DAL version and, as @dpgeorge says, needs to be updated.

@deshipu Could you please file a separate issue if `pin.write_analog()` doesn't work properly.

**Comment by deshipu** [comment]
I see, sorry, it sounded similar to me. I will file an issue.

**Comment by Tonyaj** [comment]
Hi
I have been having the same problem using speech and music in same program.
Couldn’t see what I was doing wrong, then someone kindly pointed this out.
Is there any update or solution ?
Thanks
