### ISSUE TITLE
how representation 'a' in micro:bit use micro:python?

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#359]
.

**Comment by dpgeorge** [comment]
> how representation 'a' in micro:bit use micro:python?

I don't really understand this question, but if you're refering to the object representation (MICROPY_OBJ_REPR) then it's possible to change it by editting the inc/microbit/mpconfigport.h file.

**Comment by ntoll** [comment]
Hello @KimHwaMok,

Do you mean a new Python module or C module?

If you mean a Python module you can upload the Python file to the microbit using Mu (http://codewith.mu/) or microfs (https://microfs.readthedocs.io/en/latest/). Once the file is on the micro:bit's "file system" you can import it like in normal Python.

An example is given here: https://microbit-micropython.readthedocs.io/en/latest/tutorials/storage.html#mainly-main-py

Hope this help! Happy to answer more questions! :-)

**Comment by ZanderBrown** [comment]
is #360 related?

**Comment by KimHwaMok** [comment]
yes... but new one is more detailed.

2016-10-14 19:16 GMT+09:00 Zander <notifications@github.com>:
