### ISSUE TITLE
Question about custom images and characters

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#360]
I know that it's to hard to understand my question.
because i'm not English well so i was very hard that exactly write what i want.

i using Micro-Python.
my point is here.
for example if i wrote [ display.scroll("Hello World") ] so it's print out by micro:bit led
[ display.show(Image.HAPPY) ] is same too.

i want to add new Image and new Character.
so finally i want to make new library like microbitdisplay.cpp
for that reason i have to know that how to rule about print out micro:bit led

where do i have to see MicroPython library?

**Comment by ZanderBrown** [comment]
Documentation for `Image`
http://microbit-micropython.readthedocs.io/en/latest/image.html

I understand English may be a problem but could you attempt to expand a little?
May it be easier to communicate in your native language and leave the rest of us to Bing Translate ext
