### ISSUE TITLE
Consider a simple, wired microbit-to-microbit comms protocol

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#37]
It would be nice if microbits could communicate with each other.  Of course there is Bluetooth, but we don't have that feature (yet...) and even if we did it would still be good to have a wired comms option.  One could easily use pins to read and write high or low (ie a single bit) but it would be nice to have a way of sending and receiving arbitrary bytes.

At the physical layer it could be:
- I2C, needs 3 wires: GND, SCL, SDA
- UART, needs 3 wires: GND, TX, RX (or 2 if you just want one-way comms)
- One-wire protocol (or a variant thereof, implemented in software), needs 2 wires: GND, SIGNAL

I would opt for one-wire, since it uses the least wires and we can use P0 and GND for it (I2C and UART require using one of the smaller pins, I think, which are difficult to access without an edge connector socket, or a soldering iron).

At the software layer (API) it could be:

``` python
comms.any() # returnns True if any waiting bytes
comms.read() # returns all waiting bytes
comms.write(buf) # sends given bytes
```

This is a simple as it gets.  One-wire would even support multiple microbits connected to the same signal line, but without addressing it would be simple broadcast (ie everyone in a room yelling).

**Comment by markshannon** [comment]
Given that we have the radio module, is this worth bothering with now?

**Comment by dpgeorge** [comment]
I'd say this can be closed as "out of scope".  Communication can be achieved via existing uart or radio, or even simple pin I/O.
