### ISSUE TITLE
/source/microbit/microbitdisplay.cpp module

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#373]
this is a micropython display module
`DEFAULT_SCROLL_SPEED      150`

`void microbit_display_scroll(microbit_display_obj_t *self, const char* str) {`
     `mp_obj_t iterable = scrolling_string_image_iterable(str, strlen(str), NULL, false, false);`
     `microbit_display_animate(self, iterable, DEFAULT_SCROLL_SPEED, false, true);`
`}`

and i made example simple code
`import microbit`
`microbit.display.scroll('hello!)`
`dir(microbit)`

and i changed micropython display module
`DEFAULT_SCROLL_SPEED      150`

`void microbit_display_scroll(microbit_display_obj_t *self, const char* str) {`
    `const char *tmp = "test version!"`
    `mp_obj_t iterable = scrolling_string_image_iterable(tmp, strlen(tmp), NULL, false, false);`
    `microbit_display_animate(self, iterable, DEFAULT_SCROLL_SPEED, false, true);`
`}`

and rebuild!
i expected change display "hello!" to "test version!" but doesn't working :(
just show "hello!" in microbit.. not "test version!"
what is wrong in my code?

**Comment by dpgeorge** [comment]
Did you deploy the new firmware to your device?

**Comment by KimHwaMok** [comment]
new firmware?
Is this firmware problem?
If so that how to deploy new firmware in my device?

**Comment by dpgeorge** [comment]
If you recompile the code you need to reflash the microbit with the new firmware.  "make deploy" can do that but it might need to be adjusted for your system.

**Comment by KimHwaMok** [comment]
@dpgeorge 
I just deployed new firmware in my device.
but my problem is same :(

**Comment by dpgeorge** [comment]
You need to upload not the DAP link firmware, but the code for the nRF51.  The hex file found here: build/bbc-microbit-classic-gcc-nosd/source/microbit-micropython.hex

**Comment by KimHwaMok** [comment]
@dpgeorge 
Okay, first i found microbit-micropython.hex file.
what should i change this file?

**Comment by dpgeorge** [comment]
You need to download this file to the microbit, copy it to the mass storage device.

Sorry but I can't help you further beyond these instructions.

**Comment by KimHwaMok** [comment]
@dpgeorge 
I understand
thank you for reply

sudo cp build/bbc-microbit-classic-gcc-nosd/source/microbit-micropython.hex /dev/ttyACM0

**Comment by KimHwaMok** [comment]
@dpgeorge 
I have last question.
I followed you step everything.

i copied microbit-micropython.hex file in my mass storage device...
but but!!
i same problem...

**Comment by ntoll** [comment]
Hi @KimHwaMok,

Just checking some very basic things to make sure you have everything set up correctly.

* You use `make build` to compile your code?
* If `make build` works you'll find a `firmware.hex` file in the `/build` directory.
* Copy the `firmware.hex` file to your micro:bit - this will flash *your* modified version of MicroPython onto the device.
* Try your Python code and do a little dance when it works! :-)

Sorry if all the above is obvious to you, I just want to make sure all the basics are in place.

**Comment by deshipu** [comment]
> @dpgeorge 
> I understand
> thank you for reply
> 
> sudo cp build/bbc-microbit-classic-gcc-nosd/source/microbit-micropython.hex /dev/ttyACM0

No, this is wrong. The `/dev/ttyACM0` is the serial device. You want the block storage device -- the one that gets mounted somewhere in `/media` as a disk.

**Comment by KimHwaMok** [comment]
@ntoll 

make build?
what is `yotta build`???

I always change /source/microbit/microbitdisplay.cpp then use `yotta build` again

**Comment by KimHwaMok** [comment]
@deshipu 

thank you
In my case /media/xxx/microbit

**Comment by ntoll** [comment]
Sorry, that should be `make all` (I was mis-remembering). Or better, `make yotta`. It wraps `yotta builb` with some useful stuff. Just look in the `Makefile` and you'll see.

**Comment by KimHwaMok** [comment]
@ntoll 
oh my god,

i tried to `make all, make yotta` finally i found /build/firmware.hex

**Comment by ntoll** [comment]
Great stuff... now copy it onto your device and try it out! :smile:

**Comment by KimHwaMok** [comment]
@ntoll 

Maintenance mode!! am i right???
