### ISSUE TITLE
Docs do not list the set_pull methods

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#381]
The docs here:

https://microbit-micropython.readthedocs.io/en/latest/pin.html#pin-functions

do not list the set_pull() method.

From python-microbit mailing list...

Hi David,

Looking at the code the default pull states seem to be:

read_analog: configured by mbed analogin_init() function, looks like
there is no pull
read_digital: PULL_DOWN
is_touched: PULL_UP

To change the value, use: pin.set_pull(pin.PULL_UP), or PULL_DOWN or NO_PULL.

**Comment by ntoll** [comment]
See #382 :-)

**Comment by dpgeorge** [comment]
I forgot to note that this issue was originally raised by @whaleygeek, I just reposted it here.
