### ISSUE TITLE
source/microbit/microbitdisplay.cpp

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#394]
I modified the scroll function of [source/microbit/microbitdisplay.cpp]
Hence, [./tools/pyboard.py /dev/ttyACM0 ./examples/test.py] output is always string 'XXXX'

However, it is not the expected output in other environments, rather than Ubuntu. 
ex) [https://www.microbit.co.uk/app/#edit:57549027-fb52-40bd-815c-4c552b886318]
If I input string 'aaaa', the output is string 'aaaa 'too.

I wonder why this problem occurs.

**Comment by dpgeorge** [comment]
If you modify the C/C++ code then it's very likely you change the behaviour.  This is not a bug/issue.  Instead, please discuss general usage of the microbit at the forum or on the mailing list.  Thanks!
