### ISSUE TITLE
ValueError: pin0 is in music mode

### ISSUE THREAD

**Issue by shenki** [bbcmicrobit/micropython#398]
With code that looks like the following, we have occasionally seen `ValueError: pin0 is in music mode`:

```python
while True:
  music.play(music.NYAN, wait=False)
```

**Comment by dpgeorge** [comment]
@markshannon I took a quick look at the code and it seems like microbit_obj_pin_acquire will raise an exception when trying to set a pin to the mode that it's already in.  I'd say it should succeed in this case.

Also, these pin acquire/free functions should be surrounded by IRQ disable/enable pairs if they are going to be called from the ticker IRQ.

**Comment by tsukasa-au** [comment]
I have found that by forcing the async music state back to idle, then calling microbit_obj_pin_release before setting up the async state again.

You can see this in 704ba76320b3be8a41798a253d50acffed30efe9.

**Comment by dpgeorge** [comment]
This is still a problem with music.pitch, eg:
```
>>> import music
>>> music.pitch(440)
>>> music.pitch(440)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Pin 0 in music mode
```
