### ISSUE TITLE
compass.heading() causes subsequent code to be rejected as syntax error

### ISSUE THREAD

**Issue by markshannon** [bbcmicrobit/micropython#408]
This is a pretty serious bug as it makes the compass completely unusable.

```
>>> compass.heading() # Rotate microbit until it is happy...
302
>>> a+b
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
```
Reseting the microbit does not fix the problem
```
MicroPython v1.7-9-gbe020eb on 2016-04-18; micro:bit with nRF51822
Type "help()" for more information.
>>> a+b
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
```
which rather suggests that the firmware is getting mangled.
Re-flashing fixes the problem (until the compass is calibrated)

This first appeared with https://github.com/bbcmicrobit/micropython/commit/c7e443bae1a59ec6b35f4a16f4ea7d473fac3a60
although it seems highly unlikely that commit was responsible.
I think that it merely exposed the underlying problem.

**Comment by dpgeorge** [comment]
Fixed in merge of version1 branch at e26d7c89d4a96de0fa0a1dd5aec024b31fc4816e
