### ISSUE TITLE
What encoding method do micropython use?

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#409]
My development environment is Ubuntu 16.04 [64bit].
I am developing micro-bit that supports multiple languages.
What encoding method do micropython use in micro:bit?

`setlocale(LC_ALL, "??????????");`

**Comment by dpgeorge** [comment]
Unicode strings are encoded using utf8.

**Comment by KimHwaMok** [comment]
Hi, @dpgeorge Thank you for reply!
Can i use [setlocale, mbtowc] function in mycropython?

**Comment by dpgeorge** [comment]
> Can i use [setlocale, mbtowc] function in mycropython?

No, there is no concept of locale.  You'll need to implement it yourself in (Micro)Python.

**Comment by KimHwaMok** [comment]
@dpgeorge Thank you for reply again!
In source/microbit/microbitdisplay function, I implemented it like this:

`#include <locale.h>
setlocale(LC_ALL, "");
mbtowc(0, 0, 0);`
The locale function is defined in locale.h. 
And when I rebuild using "make all", I did not get an error.
Do I still have to implement the locale function myself?

**Comment by dpgeorge** [comment]
I don't know if setlocale or mbtowc is implemented by the provided stdlib (newlib).  If you are going this deep then you need to try it out for yourself and see what works.

**Comment by KimHwaMok** [comment]
@dpgeorge thank you again.
Okay. I got it. After the test, we will inform you of the result.

**Comment by KimHwaMok** [comment]
Hi @dpgeorge !
I think "setlocale" function in "<locale.h>" is defined in MicroPython but not implemented yet.
so, I have to implement that function in MicroPython. (setlocale)

Do you have any idea about implement setlocale function in MicroPython?

**Comment by dpgeorge** [comment]
> Do you have any idea about implement setlocale function in MicroPython?

No, sorry.
