### ISSUE TITLE
Audio module docs does not appear in contents page

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#414]
The audio module does not appear in the contents page of the docs. If I search for Audio, it finds the docs page, but if I look at the scrolling list on the far left of the docs, it is not there.

**Comment by microbit-rosslowe** [comment]
`checking consistency... /.../micropython/docs/audio.rst: WARNING: document isn't included in any toctree`

Adding to the 'API reference' section in index.rst should resolve this:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/30410608/46532322-3683ed80-c898-11e8-92ea-06716e07d40d.png">

See PR above.

**Comment by microbit-carlos** [comment]
This is now covered in PR https://github.com/bbcmicrobit/micropython/pull/578 instead of #573.

**Comment by DavidWhaleMEF** [comment]
Do we have an ETA of when the readthedocs pages will go live with this fix @carlosperate .. Thanks :-)

**Comment by DavidWhaleMEF** [comment]
Excellent work, well done team!!!
