### ISSUE TITLE
audio module documentation does not match the code (pins parameter)

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#415]
The documentation for Audio says it has a 'pins' parameter, taking a tuple of two pins to connect the speaker to...
![screen shot 2017-03-08 at 20 35 55](https://cloud.githubusercontent.com/assets/25079586/23722930/2234d16a-043f-11e7-8e0c-f1387370852e.png)

However, if I use the pins parameter like described in the docs, I get an error.

>>> audio.play(repeated_frame(triangle, 1500), pins=(pin0, pin1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: extra keyword arguments given

If I however use a pin= parameter with a single pin, it does indeed play the AudioFrame on that one pin.

audio.play(repeated_frame(triangle, 10), pin=pin1)

Is it no longer possible to play audio frames on two pins?

**Comment by DavidWhaleMEF** [comment]
Note, if I press the HELP button in Mu, it tells me this is the version I have installed...

https://codewith.mu/help/0.9.12/

I can't see anything on the codewith.mu web page that tells me what the latest version number is, to know whether I have the latest version installed or not.

**Comment by ZanderBrown** [comment]
Working out Mu version is something we have been discussing.

By checking the releases on Mu's GitHub page you can see the latest is `v0.9.13`

**Comment by DavidWhaleMEF** [comment]
Yeah, that's why I pressed the help button, it was you or carlos that suggested that (useful!) temporary trick, thanks!

We can't expect teachers and 11 year old children to instinctively know where the github pages are or indeed how to interpret them. I think if we have a downloads page, it should be obvious what the version number of the download is, so that you can check whether the version you have installed needs updating or not. Especially if we regularly use the line 'are you using the latest version' - it needs to be obvious for the target audience how they check if they have the latest version or not.

Otherwise you have to download the package and run it to work out what version the latest one is, and then press the HELP button in your old Mu and see what web page it goes to to see if you have the latest, and press the HELP button in the new one to see what version it is.

I'm sure it would be possible to make this (common) workflow much simpler for the users, don't you think? Thanks.

**Comment by ZanderBrown** [comment]
![image](https://cloud.githubusercontent.com/assets/17074021/23725480/a3cfb204-0448-11e7-8cb5-3ac617cb5d0b.png)
@DavidWhaleMEF off topic but are you seeing some odd timestamps on @GitHub

**Comment by DavidWhaleMEF** [comment]
@ZanderBrown No, I think it's your end only, I see this...

![screen shot 2017-03-08 at 21 48 06](https://cloud.githubusercontent.com/assets/25079586/23725541/f047d22e-0448-11e7-83b2-c3aaad162506.png)

**Comment by ZanderBrown** [comment]
interesting i see this page as:
![screencapture-github-bbcmicrobit-micropython-issues-415-1489006727077](https://cloud.githubusercontent.com/assets/17074021/23726017/a0e1314c-044a-11e7-9707-c242c46df659.png)

**Comment by DavidWhaleMEF** [comment]
Hey @ZanderBrown you've just invented the time travel module! Quick, check it into github and get it into the next release!!!

**Comment by ntoll** [comment]
Folks, just a polite notice to NOT mix up issues.

Mu issues belong in the Mu repos, MicroPython issues belong here and cute photos about GitHub really being run on a TARDIS should perhaps go on the microbit@python.org mailing list for everyone to enjoy. ;-)

While *I* know it's fun, and I'm often guilty of this myself, given the lack of time many of us currently have, trying to wade through a large number of emails/messages that are orthogonal to the original issue just takes up time.

To be clear, I'm not being a meanie and saying don't report issues or post GitHub screenies -- we want this project to be fun for all concerned! Rather, so that some poor bugger doesn't have to wade through all the messages only to discover they're fun chatter rather than more details of an audio module documentation bug, then can we just think about the medium we use for such friendly chatter!

Thanks!

:-)

**Comment by DavidWhaleMEF** [comment]
@ntoll - the original issue is a micropython issue though - the docs don't match the code - this is nothing to do with Mu. I only provided the mu version so that there was *some* chance of someone tracing back to the version of micro:python that I am referring to!

**Comment by ntoll** [comment]
:man_shrugging: Sure, but then the conversation veered off onto how you can tell what version of Mu is being used.

**Comment by microbit-carlos** [comment]
Looks like the function signature documentation needs to be changed to:
```
audio.play(source, wait=True, pin=pin0, return_pin=pin1)
```

@DavidWhaleMEF could could check if that resolves your original issue?

**Comment by DavidWhaleMEF** [comment]
@carlosperate That was a long time ago! I'm happy that if you have tried this and it works, then it's a docs issue. I'll note for future reference if I use this feature again to try it, but the project was so long ago now i forget what I was even trying to do! Thanks.
