### ISSUE TITLE
Need to change default accelerometer range to 8g

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#425]
How do we change the default accelerometer range to 8g in MicroPython?

PXT has a feature which calls the underlying DAL service to change the accelerometer range - what is the equivalent service in Micropython?

![screen shot 2017-04-03 at 23 20 24](https://cloud.githubusercontent.com/assets/25079586/24634185/634fa2d0-18c4-11e7-8746-2a2fc3a00908.png)

The customer doesn't want the 3g/6g/8g gestures, they actually want to measure the full range from 0g to 8g for a motion experiment using a trolley, so they need real readings (just the gesture is not enough).

How do we do this?

**Comment by dpgeorge** [comment]
> How do we change the default accelerometer range to 8g in MicroPython?

Put simple, you can't, it's not exposed in the Python API.  Please see #264 and #306 (and related #343).
