### ISSUE TITLE
Misleading wiring diagram for NeoPixels

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#459]
This image is slightly misleading...

https://github.com/bbcmicrobit/micropython/blob/master/docs/neopixel-croc.png

It shows a banana plug labelled 5V connected to the 3V pad. 

This may give the impression to users that they can back-power the micro:bit from 5V using this connector (which is definitely not the case and damage will occur if they do).

The data sheet labels it as VDD

https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf

![screen shot 2017-07-25 at 17 12 03](https://user-images.githubusercontent.com/25079586/28582189-7024cf4e-715c-11e7-981a-a692f1dabc34.png)

Also note, depending on which specific variant of the ws2812 you get, the supply voltage is out of spec if powered directly from a micro:bit - although in practice the lower voltage version does actually work regardless.

But I think that labelling the wire 5V is misleading and could lead to some damage if mis-interpreted by users.

**Comment by carlosperate** [comment]
I agree that VDD is probably a better name. As you note here, it would also be helpful to add that the voltage provided by the micro:bit is slightly lower than that required by the nexopixels (same goes with servos, most 5v ones should work, but not all do) and the fact that a battery powered micro:bit will drop the provided voltage as the battery drains.

The diagram was made with https://pycomic.github.io/microbit.html , but this web app does not offer labels for the pin, so we might have to edit the image anyway.

**Comment by ntoll** [comment]
@carlosperate that's precisely what I did (used the GIMP to add labels). If it would be handy, it's relatively easy to add text to an SVG such as the one used at the website.

**Comment by Neon22** [comment]
if it is svg then inkscape will do the job more effectively IMHO.
- https://inkscape.org

**Comment by jaustin** [comment]
How about this:
![neopixel-croc](https://user-images.githubusercontent.com/147113/47076697-37e9da00-d1f7-11e8-9d2f-18c820f646de.png)
I'll also upload the SVG to the docs with the commit so that people can generate these labelled images based on the source too:
[neopixel-croc.zip](https://github.com/bbcmicrobit/micropython/files/2486683/neopixel-croc.zip

**Comment by DavidWhaleMEF** [comment]
LGTM

Do we need to signpost the potential voltage mismatch to users in some way (either here or on tech site, or as a kbase article?) We had a lot of chatter and mis-information in the various communities about this, and the problem is worse if you run the micro:bit off of batteries due to the depressed cell voltage, and differently worse if running off USB due to the lower advertised available current. Perhaps a kbase would be better for that issue?

**Comment by jaustin** [comment]
Yea, I'll factor that into the docs when I change the image over and we can discuss in review in a PR. Gives us a nice chance to talk about blue LED 'on' voltages and batteries discharging which I think fits nicely with the style of the MicroPython docs where they tell you about adjacent/useful things as well as just the API.

**Comment by microbit-carlos** [comment]
PR #596 has been merged, thank you everyone!
