### ISSUE TITLE
Published docs are out of date with the deployed code version

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#464]
The version of the docs published are not in step with the version of the codebase currently deployed.

https://codewith.mu/ gives me 0.9.13 of Mu, it's not clear to me which version of MicroPython-microbit is built into that package as I can find no traceability.

The docs here http://microbit-micropython.readthedocs.io/en/latest/ describe features that are not available in the currently deployed codebase within codewith.mu or python.microbit.org

See: https://github.com/bbcmicrobit/micropython/issues/463

The micro:python API is moving to version 1.0, but this message seems to have been there for months?

![screen shot 2017-08-24 at 10 14 03](https://user-images.githubusercontent.com/25079586/29659080-022ab9de-88b5-11e7-92c2-9a6dc3878e44.png)

Speech is still ALPHA code?

![screen shot 2017-08-24 at 10 14 40](https://user-images.githubusercontent.com/25079586/29659104-138b48b0-88b5-11e7-9355-fd75a35cc855.png)

**Comment by DavidWhaleMEF** [comment]
@jaustin is this in hand, do you know? Thanks.

**Comment by lgnativs** [comment]
I have the same problems.

**Comment by microbit-carlos** [comment]
The master version of the docs (for v1.0) should then remove these warnings.

**Comment by microbit-carlos** [comment]
Both of these are covered in PR #567.

**Comment by nealmcb** [comment]
Are there any docs still out-of-date with MicroPython 1.0.0 release? Or should this be closed so the 1.0.o milestone can be cleaned up....

**Comment by microbit-carlos** [comment]
The docs are now in sync, thanks for bringing this up @nealmcb! I'll close this issue :)
