### ISSUE TITLE
Micropython can not work when powered by the battery.

### ISSUE THREAD

**Issue by ouki-wang** [bbcmicrobit/micropython#471]
I have compiled  Micropython firmware but found nrf51822 cannot work when powered by the battery;
however, it won't happen when used firmware wrote by others. 

What caused the problem?

**Comment by ouki-wang** [comment]
Why connect TGT_NRESET to p0.19 of nrf51822?
I could not find corresponding codes.

**Comment by dpgeorge** [comment]
> I have compiled Micropython firmware but found nrf51822 cannot work when powered by the battery;
> however, it won't happen when used firmware wrote by others.

You'll need to give more detail about your problem: what board you use, which firmware version of MicroPython, what script you are using, which "other" firmware is working, and what exactly are the symptoms when it doesn't work.

> Why connect TGT_NRESET to p0.19 of nrf51822?
> I could not find corresponding codes.

Please explain in more detail your issue/question.

**Comment by ouki-wang** [comment]
My source code commit id is 50c41dee2791d1521e793132232951da37fdee65 which has been compiled to firmware A.

The other firmware: the built-in mu-1.9.13 version as firmware B.

Compared with firmware B, only the firmware A could not work well when powered by the battery. 

Below is the firmware A phenomenon:

1. When power-supplied by USB, TGT_NRESET voltage is 3.1V which nrf51822 recognized as a high level. 

2. When  power-supplied by 3.7V lithium battery, TGT_NRESET voltage is 2.0V while nrf51822 would not recognize it as a high level.

3. You can use Micropython when comment source code related to resetButton.

After preliminarily analyze, I guess 2.0V cannot been recognized as a high level voltage. Moreover, the soft reset bottom should not been comment. How could I solve this problem?

**Comment by dpgeorge** [comment]
@ouki-wang thanks for the details about the problem.

> You can use Micropython when comment source code related to resetButton.

Where is the code related to the reset button that you refer to here?

Can you please try using "version1" branch of this repository, the commit c8c4db8444fa35cda2bbca94b703be7469b666fe, and see if that works when running from a battery?

**Comment by ouki-wang** [comment]
@dpgeorge thanks for your reply
MicrobitDisplay.cpp
                //burn cycles
                while(i>0)
                {
                    // Check if the reset button has been pressed. Interrupts are disabled, so the normal method can't be relied upon...
                    if (resetButton == 0)
                        //microbit_reset();//--------------here----------

                    i--;
                }

MicrobitSupperMain.cpp
int main()
{    
    // Bring up soft reset button.
    //resetButton.mode(PullUp); // -----------here--------------
    //resetButton.fall(microbit_reset);// -----------here--------------

**Comment by dpgeorge** [comment]
What hardware are you using, is it an official microbit?  Did you check that your battery is not flat?  Did you plug it into the battery connector and what is the voltage at the VDD pin of the nRF51822?

**Comment by ouki-wang** [comment]
hardware: official microbit V1.3B
battery is good,battery voltage is 3.9V
When power-supplied by lithium battery only,  nrf51822 VDD=3.8V, TGT_NRESET=2.2V

**Comment by dpgeorge** [comment]
Are you able to try the version1 branch, commit c8c4db8444fa35cda2bbca94b703be7469b666fe?

**Comment by ouki-wang** [comment]
@dpgeorge  ok，I will try this branch。but I connect overseas sites very slow when a lot of people online。
so I need a long time to give you a reply

**Comment by ouki-wang** [comment]
@dpgeorge version1 branch-commit id c8c4db8 work well

**Comment by dpgeorge** [comment]
> version1 branch-commit id c8c4db8 work well

Great, thanks for confirming that.  That branch will become the master at some point.  It's recommended to use it now if you want to build your own firmware.

**Comment by microbit-carlos** [comment]
>hardware: official microbit V1.3B
battery is good,battery voltage is 3.9V
When power-supplied by lithium battery only, nrf51822 VDD=3.8V, TGT_NRESET=2.2V

@ouki-wang just as a general note, the maximum operating voltage of the nrf51 is 3.6V, anything above that can cause damage and the microcontroller might not work to specifications, and the recommended voltage for battery connector or edge connector is 3.0V.

That being said, glad this does work on master. Sounds like this issue can be closed.

**Comment by microbit-carlos** [comment]
`version1` branch has been merged to master in e26d7c89d4a96de0fa0a1dd5aec024b31fc4816e, so we can close this one. Thanks for the report and confirming it works with the latest versions.
