### ISSUE TITLE
error: could not locate github component "lancaster-university/microbit-dal"

### ISSUE THREAD

**Issue by amos1969** [bbcmicrobit/micropython#49]
Hi 

Running **yt up** (using Python 2.7 on Linux Mint 17.2) I now get the error:

error: could not locate github component "lancaster-university/microbit-dal", either the name is misspelt, you do not have access to it, or it does not exist

Looking at the lancaster-university page on github I can't see anything similar.

**Comment by ntoll** [comment]
This is the device access layer (DAL) that is still under the NDA.

If you would like access you need to have signed the NDA (@amos1969 - I believe you're already covered) and then Lancaster Uni can add you.

**Comment by willingc** [comment]
@ntoll Does the NDA for the DAL still apply? Getting the error of not found when running ``yt up``

**Comment by ntoll** [comment]
'fraid so (we're working on it). In the meantime, as a director of the PSF I believe you're covered by the NDA (i.e. just don't share the DAL). Ergo, I can ask Joe and/or James to add you to the repos. GitHub will ping you when they've done it (they're usually very quick). :-)

**Comment by willingc** [comment]
Sounds good. Thanks @ntoll.

**Comment by deshipu** [comment]
I would also want access to that repository, for the github user ``armmbedyotta`` (I can't use my normal user, because yotta wants access to private repositories), if it's possible?

**Comment by dpgeorge** [comment]
> I can't use my normal user, because yotta wants access to private repositories

I had similar concerns, but was convinced that giving yotta access is no less secure than, eg, logging into GitHub with Firefox.

**Comment by ntoll** [comment]
OK... I've requested you have access. You should get an email from GitHub when you're in the "club". ;-)

**Comment by dpgeorge** [comment]
Now available.
