### ISSUE TITLE
Add support for RGBW neopixels

### ISSUE THREAD

**Issue by microbit-mark** [bbcmicrobit/micropython#500]
microbit-support:#4929

Relates to https://github.com/micropython/micropython/issues/2478
Documentation for micropython https://docs.micropython.org/en/latest/esp8266/esp8266/tutorial/neopixel.html

 Neopixel constructor currently only takes 2 arguments

**Comment by paulbaumgarten** [comment]
I've just come across this issue. Our school ordered a bunch of Neopixels without realising they were the RGBW variety. Is there a known hack to get this working at present?

**Comment by dpgeorge** [comment]
See PR #691 for an implementation.

**Comment by microbit-carlos** [comment]
Closing as implemented 🎉
