### ISSUE TITLE
Clarify semantics of button is_pressed() methods

### ISSUE THREAD

**Issue by bradleyjkemp** [bbcmicrobit/micropython#507]
From the docs (https://github.com/bbcmicrobit/micropython/blob/master/docs/button.rst) I'm unsure what the different meanings of "pressed" are.

Assuming there are two physical button states "up" and "down" (i.e. circuit disconnected and circuit connected).
The meanings of was_pressed() and get_presses() seem clear: has there been an "up"->"down" transition since the method was last called and the count of these transitions respectively.

But what does is_pressed() mean? Does that return true for as long as the button is in the "down" state?

**Comment by dpgeorge** [comment]
Thanks for flagging this issue.  I've tried to address it in e3472aadee2ea9f2ddf6c849d228fd6f2b5721e7 by making the docs more explicit.

Probably `is_pressed()` should be called `is_held()`, but we can't change it now :)
