### ISSUE TITLE
Downloading and making python module

### ISSUE THREAD

**Issue by HelloWorld-py** [bbcmicrobit/micropython#508]
Upon struggling for 3 hours I have given up. I followed this tutorial (https://www.youtube.com/watch?v=sHO0IWbAuYg) to get yotta set up but once i did I was still unable to get the micropython module to compile, can someone please make an executable to do all of this or a pip module in python?

**Comment by ukBaz** [comment]
I am not sure I understand what you are trying to do.
Are you trying to write Python to run on the micro:bit?
  - Then the [Mu editor](https://codewith.mu/ ) is a simple way to start with this [getting started video](https://www.youtube.com/watch?v=zmOxOusMvjo)

Are you trying to write programs for the micro:bit in C/C++?
  - Then using the arm mbed online editor might be a good place to start https://os.mbed.com/platforms/Microbit/
  - Or if you want offline then there are instructions at: https://lancaster-university.github.io/microbit-docs/offline-toolchains/

**Comment by HelloWorld-py** [comment]
Ideally I wanted to be able to edit my code in Pycharm and compile it offline, I will try the Mu editor though, thank you!

**Comment by MrYsLab** [comment]
@HelloWorld-py I use PyCharm for all my Python development which includes PCs, the micro:bit and esp8266. Python is an interpreted language and therefore is not compiled off-line.

With PyCharm you can use the MicroPython plugin or, installing some external tools. I wrote an article on how to do this [here](https://mryslab.github.io/pseudo-microbit/). Note that you cannot attach the PyCharm debugger to the micro:bit.  You will need to use the REPL or something like the LED matrix to indicate what is happening internally.

**Comment by ukBaz** [comment]
You might both be interested in the following blog where they announced the MicroPython Plugin for PyCharm

https://blog.jetbrains.com/pycharm/2018/01/micropython-plugin-for-pycharm/
