### ISSUE TITLE
Use Neopixels on more pins?

### ISSUE THREAD

**Issue by sofiania** [bbcmicrobit/micropython#517]
Can 3 neopixels with 8 LEDS be connected simultaneously to say pin 0, pin 1, pin 2?

**Comment by dpgeorge** [comment]
Yes that should be possible.  Give it a try!

**Comment by rhubarbdog** [comment]
be careful, 3*8 neopixel may pull 2 amps of power, you'll need an external power supply for your LED's

**Comment by rhubarbdog** [comment]
Try any of these pins they are all PWM capable and aren't connected to anything else
pin0, pin1, pin8, pin2, (pin13, pin14, pin15) & pin16
You can use any of the pins which support write_analog, but you would need to start disabling display, not using the buttons etc

**Comment by microbit-carlos** [comment]
@sofiania I assume you've been able to run neopixels on several pins without issues, so I'll close this one.
However, please let us know if you've encountered any problems and we can reopen it.
