### ISSUE TITLE
Reset button is ignored on battery power

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#546]
When on battery power pressing reset does nothing with 
versions 1.7.9 that was shipped with mu 1.0.0 beta 12 and
MicroPython v1.9.2-34-gd64154c73 on 2017-09-01; micro:bit v1.0.0-rc.2 with nRF51822
Whilst using site https://python.microbit.org/v/1 or the equivalent program in microsoft makecode blocks.  The reset button works on battery

**Comment by dpgeorge** [comment]
Thanks for the report.   Indeed we must configure the soft reset button manually at start up.  See #550 for a patch that does this.

Note that there is a slight difference with reset behaviour when running on battery: the reset occurs as soon as you press the button, whereas when running on USB holding the reset button down will hold the device in reset until you let go of the reset button.  This may have real consequences for users, eg they want to start a timer upon reset and hold down the reset button until they are ready to start timing. To have the same behaviour on battery the start-up code could check if reset is held down and wait until it is released before it starts executing.  The downside of doing this is that it's different to how the C++ code would work (and how makecode works).

**Comment by dpgeorge** [comment]
> taking in consideration that DAL and MakeCode and MicroPython v0.9 reset as soon as the button is pressed, then it's probably better to keep the same behaviour

Yes I agree, best not to change behaviour now.
