### ISSUE TITLE
Update pin documentation to include info about pins 5 and 11 external pull ups

### ISSUE THREAD

**Issue by microbit-carlos** [bbcmicrobit/micropython#558]
https://microbit-micropython.readthedocs.io/en/latest/pin.html

The buttons on pins 5 and 11 also contain 10K external pull up, so we can add a note at the end of that page to also include this information.

**Comment by Isioviel** [comment]
I'm submitting a pull request for this issue.

**Comment by microbit-carlos** [comment]
Updates to the documentation from #559 have already been merged, thank you @Isioviel!
