### ISSUE TITLE
Update docs to include (relevant) info about micropython module

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#590]
I could not find any documentation about the micropython module in the BBC microbit micropython API docs on read the docs.

Related to this PR where I discovered this fact: https://github.com/bbcmicrobit/micropython/pull/588

These are the methods that the micropython module on micro:bit supports (taken from REPL from an image flashed from latest python.microbit.org today)

```
>>> import micropython
>>> help(micropython)
object <module 'micropython'> is of type module
  __name__ -- micropython
  const -- <function>
  opt_level -- <function>
  mem_info -- <function>
  qstr_info -- <function>
  stack_use -- <function>
  heap_lock -- <function>
  heap_unlock -- <function>
  kbd_intr -- <function>
```

So, ignoring __name__, you can get the official docs from here:

http://docs.micropython.org/en/latest/library/micropython.html

But note that page includes a number of other methods that are not supported on the micro:bit. We should probably also check that method, parameters and description on this core page match what is implemented on  the micro:bit, but it will be a good start.

**Comment by carlosperate** [comment]
Hi David, 
PR https://github.com/bbcmicrobit/micropython/pull/578 covers this documentation, please have a look and comment in case there is something missing or that we can improve.
