### ISSUE TITLE
Can MicroPython have a built-in SCISSORS Image?

### ISSUE THREAD

**Issue by microbit-giles** [bbcmicrobit/micropython#602]
MakeCode has a built-in scissors icon, can micro:bit Python to have one to match?
<img width="253" alt="screenshot 2018-11-22 at 14 48 21" src="https://user-images.githubusercontent.com/42380137/48909642-b88a9e80-ee65-11e8-8ea3-bb8c9b5d326e.png">

It would makes coding rock, paper, scissors simpler - or SQUARE_SMALL, SQUARE, SWORD as I am currently calling it! - and would improve consistency between platforms.

I am developing resources that are bi-lingual (Python and Javascript Blocks) and this would also help in that endeavour.

**Comment by dpgeorge** [comment]
Scissors icon added in 5005880aa3acd5e1fde9b09b9de85932e65353f1
