### ISSUE TITLE
Image aliases for ROCK and PAPER

### ISSUE THREAD

**Issue by microbit-giles** [bbcmicrobit/micropython#603]
Can we add ‘aliases’ so Image.ROCK produces the same image as Image.SQUARE_SMALL and Image.PAPER was the same as Image.SQUARE ?

This would further simplify making a rock, paper, scissors game and make MicroPython even more accessible to more young people.

**Comment by dpgeorge** [comment]
The cost (in code space) to add these aliases is about 12 bytes per alias.  So not that much.  On the other hand, it's not so hard to explain that SQUARE looks like paper so that's why it can be used to make the game.

**Comment by microbit-giles** [comment]
That's a very fair point @dpgeorge! Probably not worth pursuing unless anyone else thinks it's a good idea.

**Comment by dpgeorge** [comment]
> I'd love that free memory for my programs.

Note that adding the alias takes 12 bytes of *flash* space, not RAM.

**Comment by rhubarbdog** [comment]
Would freeing flash increase the 8188 byte script size limit `uflash`reports. Any extra space for user code would be greatfully recieved.  The microbit has a bit of a vic 20 feel. Looks like a Commodore, feels like a Commodore,  but ain't a C64. Some of the smaller machines available when i were a boy shouldn't have existed.

**Comment by dpgeorge** [comment]
> Would freeing flash increase the 8188 byte script size limit `uflash`reports.

No, that size is fixed.  Instead you can put your code on the device's internal filesystem as main.py (and also put libraries in separate files), then you have more space to use.  Mu supports this feature now.

**Comment by dpgeorge** [comment]
Note that SCISSORS was added in 5005880aa3acd5e1fde9b09b9de85932e65353f1

**Comment by microbit-carlos** [comment]
I think this can be closed now, thanks everyone!
