### ISSUE TITLE
This should be an IndentationError

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#611]
This code generates a `SyntaxError`, but it should create an `IndentationError`
```
class dummy():
    def __init__(self):
        self.variable = 42

    def method(self):
    # comment                                                                   
    self.variable += 1

    def __str__(self):
        return str(self.variable)

obj = dummy()

obj.method()
print(obj)
```

**Comment by dpgeorge** [comment]
Thanks for the report.  A simplified example that exhibits the same behaviour is:
```python
if x:
pass
```
This is really something to address upstream in the main MicroPython repository.  But in my opinion it's not worth fixing: it would be cost extra code for a rarely hit case.  And anyway, IndentationError is a subclass of SyntaxError, so SyntaxError is technically correct, just a less specific error.

**Comment by rhubarbdog** [comment]
Yes that's fair. Is it worth not implementing `IndentationError` at all and saving a few bytes

**Comment by microbit-carlos** [comment]
Thank you @rhubarbdog for the report and @dpgeorge for the explanation. Since it looks like the original question has been answered I'll close this issue.
