### ISSUE TITLE
The documentation for Radio is inconsistent

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#615]
Radio documentation here : https://microbit-micropython.readthedocs.io/en/latest/tutorials/radio.html
in section "Addressing" it states
"""
It’s possible to tune the radio to different channels (numbered 0-100).
"""

where as the documentation here : https://microbit-micropython.readthedocs.io/en/latest/radio.html
on the first page in the bullet list it states
"""
Messages are broadcast and received on a preselected channel (numbered 0-83)
"""

**Comment by dpgeorge** [comment]
Nice find, thank you!  Fixed in bb0903e37609d221749f1572f4f0ae6ed2f54cda
