### ISSUE TITLE
microbit.Image.SMILE has no eyes.

### ISSUE THREAD

**Issue by abee2** [bbcmicrobit/micropython#626]
`microbit.display.show(microbit.Image.SMILE)`

The above code produces the following result.

![img_0560](https://user-images.githubusercontent.com/972987/50444658-0d31a580-094d-11e9-88b3-c4f923bfac32.JPG)

I use chibi:bit (micro:bit compatible board) on [v1.1](https://python.microbit.org/v/1.1). The result is the same as micro:bit.

**Comment by dpgeorge** [comment]
As far as I can tell, this is intentional.  A SMILE image is just a smile.  For a happy face please use HAPPY.

**Comment by abee2** [comment]
Oh. I got it. Thank you for your advice.
