### ISSUE TITLE
Add doxygen developer docs

### ISSUE THREAD

**Issue by willingc** [bbcmicrobit/micropython#64]
As I was walking through the code base, I created a [Doxyfile](https://github.com/willingc/micropython-1/blob/3eddb8636b750839bed8e344057a4501e2a7241a/Doxyfile) to use with [doxygen](http://www.stack.nl/~dimitri/doxygen/) for creating documentation overviews of the code and its structure. I thought others might find it helpful or we may wish to add to the documentation.

**Comment by dpgeorge** [comment]
I'm not a big fan of Doxygen, but other people may be :)  I guess it's only useful to view docs from the DAL and/or mbed?

**Comment by ntoll** [comment]
@willingc any progress on this or can we shelve this "feature" for 0.9?

**Comment by willingc** [comment]
I wasn't planning on moving forward with this. It may be useful down the road for docs. For now, I will close.
