### ISSUE TITLE
Beta editor fails to load Python files with < 3 lines

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [bbcmicrobit/micropython#647]
The beta editor fails to load Python files with fewer than 3 lines.

The following error is on the console:

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at isPyModule (python-main.js:345)
    at loadPy (python-main.js:355)
    at FileReader.reader.onload (python-main.js:611)
```

The function `isPyModule` needs to account for the fact codeLines.length might be < 3. Array.slice might be useful.

**Comment by dpgeorge** [comment]
This should be reported at https://github.com/bbcmicrobit/PythonEditor

**Comment by microbit-matt-hillsdon** [comment]
@dpgeorge thanks & sorry!
