### ISSUE TITLE
Firmware build fails on MacOS at make echo command

### ISSUE THREAD

**Issue by diaena** [bbcmicrobit/micropython#656]
`make` generates an incorrect `VER_ADDR_FILE`: 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/10000430/55552626-cf73b400-56d5-11e9-95c4-2d7e28868b20.png">

<img width="303" alt="image" src="https://user-images.githubusercontent.com/10000430/55552585-aa7f4100-56d5-11e9-9695-b0c47c2ab7e1.png">

(It should be of the form `0x00036df2`)

This is because make uses `sh` to execute commands by default, but MacOS and Linux implement `sh` differently.
On MacOS, `sh` functionality is implemented by bash which on MacOS is compiled with `--enable-strict-posix-default` and as a result of this flag is that the `echo` command does not understand the `-n` flag.

Ways of fixing:

1. use make inbuilt echo command
2. use printf constructs instead of echo (probably nicest and most portable)
3. use the full path to `/bin/echo`

**Comment by WayneKeenan** [comment]
I just raised issue #657 and PR #658, which also fixes an `objdump` command issue,

**Comment by Frederic-soft** [comment]
There is also an issue with ```size```, which should be ```arm-none-eabi-size``` on line 16 of the Makefile.

**Comment by dpgeorge** [comment]
Fixed by dc92faf91be4cdf74130ec9144a5e5ba02d3836d and 4cd8ad10529eeec9b58b9d9ad9f39a2b177a1a35
