### ISSUE TITLE
Search results in 500 error

### ISSUE THREAD

**Issue by microbit-mark** [bbcmicrobit/micropython#679]
Attempting to search readthedocs https://microbit-micropython.readthedocs.io/en/v1.0.1/ results in 500 nginx error or 502 bad gateway cloudflare error.

clicking on project home also has the same result
![Screenshot 2020-06-15 at 08 28 19](https://user-images.githubusercontent.com/31242877/84629444-30a23480-aee2-11ea-861e-aa0234e5bb52.png)
Links to
https://readthedocs.org/projects/microbit-micropython/?fromdocs=microbit-micropython

Fileysystem API link also errors https://microbit-micropython.readthedocs.io/en/v1.0.1/filesystem.html

Firefox 77 on Mac 10.15
Tried v1.0.1 and latest docs

**Comment by microbit-mark** [comment]
Now appears not to reproduce

**Comment by microbit-mark** [comment]
Seems to have been fixed https://readthedocs.org/ doesn't seem to offer an indication of the status. They say that hosting is provided by Azure.

I'll feedback about having some kind of status page, but closing this ticket

**Comment by microbit-mark** [comment]
https://github.com/readthedocs/readthedocs.org/issues/7192

**Comment by microbit-carlos** [comment]
Thanks for keeping an eye on this and the feature request Mark!
