### ISSUE TITLE
Ensure random() is truely random

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#68]
There is an issue with the DAL implementation of `random()`. We should supply an up-stream patch to fix this.

**Comment by whaleygeek** [comment]
Yes, it's not very random at all at the moment. My Dalek game always (reliably) shoots me on the first two attempts, implying to me that the random is not correctly seeded?

**Comment by ntoll** [comment]
@whaleygeek hey hey... good to have your input! It turns out that @dpgeorge found a bug in the DAL implementation of the RNG but it's not yet been fixed.

**Comment by ntoll** [comment]
Appears to be fixed upstream here: https://github.com/lancaster-university/microbit-dal/pull/46

**Comment by dpgeorge** [comment]
I have verified that the patch works and random is now random (enough)!
