### ISSUE TITLE
Add was_pressed(), get_presses() and reset() methods to buttons.

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#69]
Put simply, pull request #53 needs to be fixed / merged.

**Comment by willingc** [comment]
To clarify for others that are new to these issues, new methods for buttons should be added to the code base. The methods needed are:
- [ ] was_pressed()
- [ ] get_presses()
- [ ] reset()

I believe that @markshannon is working on this per message on #53.

**Comment by dpgeorge** [comment]
I think it should be called "reset_presses()".

**Comment by willingc** [comment]
@dpgeorge +1

**Comment by markshannon** [comment]
Fixed by https://github.com/bbcmicrobit/micropython/issues/101
