### ISSUE TITLE
Consider allowing microbit.sleep to take a float

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#7]
microbit.sleep currently only accepts an integer, since the underlying DAL only accepts an integer argument.

Maybe it makes sense to allow a float and implicitly truncate it to an int?

@ntoll what is your opinion?

**Comment by dpgeorge** [comment]
What about this?  I still think microbit.sleep should be allowed to take a float (representing a fraction of a microsecond).  That way people can use float maths to compute the sleep time and not need to cast to an integer.

**Comment by ntoll** [comment]
+1

**Comment by markshannon** [comment]
+1 as well

**Comment by ntoll** [comment]
It appears the "idea is resolved" (to quote @dpgeorge). :-)

**Comment by dpgeorge** [comment]
Implemented, see above.
