### ISSUE TITLE
Dictionary: I can't add new entry.

### ISSUE THREAD

**Issue by t-789** [bbcmicrobit/micropython#708]
Hello! I created a dictionary on micro:bit, and I found out that I can't add a new entry to a dictionary. Here are my code: 
Cars = {"a1": -1,
        "a2": -1,
        "a3": -1,
        "b1": -1,
        "b2": -1,
        "b3": -1,
        }

Cars['a1a'] = input.running_time()

Cars['a1b'] = 100

And the editor said: 
![issue picture](https://user-images.githubusercontent.com/49603635/107371569-60f8ac00-6b1f-11eb-9684-d2f1cffdee7d.jpg)

**Comment by microbit-carlos** [comment]
Hi @t-789,

Thanks for the report. It looks like you might have been using the Python version of MakeCode, right?
This repository is MicroPython which can be used in the [online Python editor](https://python.microbit.org), [Mu editor](https://codewith.mu), etc. 
For issues with MakeCode you can open a new ticket in https://github.com/microsoft/pxt-microbit/issues

**Comment by t-789** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
