### ISSUE TITLE
Microbit Low Power Mode

### ISSUE THREAD

**Issue by TDanielI** [bbcmicrobit/micropython#726]
In https://tech.microbit.org/software/spec-power-management/ it is mentioned that in order to enter the Deep Sleep Mode, it can be accessed through "User code calling a CODAL uBit method". Is there a spesific syntax for this or is this just the normal sleep()?
Thank you.

**Comment by microbit-carlos** [comment]
Hi @TDanielI,

This advanced power management is micro:bit V2 feature and this repository contains the MicroPython project for micro:bit V1.

You can find the micro:bit V2 CODAL API for power management in the https://github.com/lancaster-university/codal-microbit-v2/ repository:
https://github.com/lancaster-university/codal-microbit-v2/blob/master/inc/MicroBitPowerManager.h

If you have any questions about the CODAL API that would be the best place to open an issue, and if you have questions about the MicroPython for micro:bit V2 API for power management the best place would be https://github.com/microbit-foundation/micropython-microbit-v2/issues .

Thanks!
