### ISSUE TITLE
Allow persistent storage in flash

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#73]
It should be possible to use flash based persistent storage to squirrel away "stuff" between resets. Perhaps a very simple key/value store that looks like a dictionary to the end user would suffice?

**Comment by dpgeorge** [comment]
Main thing to know for this is: what is the page-erase size on the nrf51?  That will dictate how it's done.  Maybe we also want some kind of simple wear-levelling.

**Comment by whaleygeek** [comment]
From the NRF51 datasheet, the device will support 20,000 erase cycles. The smallest write size is a 32 bit word. Page (and therefore erase) size is 1024 bytes at a time. The MPU supports protected regions in 4kB chunks.

**Comment by ntoll** [comment]
@dpgeorge did I imagine this, or has this been completed..?

**Comment by dpgeorge** [comment]
It's not implemented, not even in the DAL.

**Comment by ntoll** [comment]
OK. I must have mis-remembered a commit message.

**Comment by markshannon** [comment]
Superseded by https://github.com/bbcmicrobit/micropython/issues/246
