### ISSUE TITLE
we neeed arc-tangent on microbit

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#758]
i want to make a mecca detector for microbit
simply input your longtitude and lattitude
using the compas and arc tanget calculate the shortest distance to mecca

**Comment by microbit-carlos** [comment]
Hi @rhubarbdog,

The `math` module already contains `atan()` and `atan2()`:

```
MicroPython 569e361 on 2022-06-20; micro:bit v2.0.0 with nRF52833
Type "help()" for more information.
>>> import math
>>> math.a
acos            asin            atan            atan2
```

Are those the functions you meant? Or is it a different one?

**Comment by microbit-carlos** [comment]
Hi @rhubarbdog, did my previous reply answer your question?

**Comment by rhubarbdog** [comment]
yes thanks
