### ISSUE TITLE
New Feature: Function to scale values with different ranges

### ISSUE THREAD

**Issue by microbit-carlos** [bbcmicrobit/micropython#761]
To match the V2 implementation discussed in https://github.com/microbit-foundation/micropython-microbit-v2/issues/102

**Comment by microbit-carlos** [comment]
Docs PR:
- https://github.com/bbcmicrobit/micropython/pull/762

**Comment by dpgeorge** [comment]
Implemented in 256520fbc02a3004eb269a165d94e856016861f5
