### ISSUE TITLE
whats the biggest floating point number

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#777]
i've tried
```
import sys
print(sys.float_info)
```
there is no float info so i need to hard code it or is there another way to determine `sys.float_info.max_10_exp`

**Comment by dpgeorge** [comment]
The biggest is about `3e38` (because it's a single precision float).

**Comment by rhubarbdog** [comment]
thanks

**Comment by microbit-carlos** [comment]
I'll mark this issue as resolved then, thanks Damien!
