### ISSUE TITLE
what about microREPL?

### ISSUE THREAD

**Issue by rhubarbdog** [bbcmicrobit/micropython#782]
shouldn't instructions for `microrepl` be included on this page https://microbit-micropython.readthedocs.io/en/v2-docs/devguide/repl.html

**Comment by microbit-carlos** [comment]
Yes, we can add that to the https://microbit-micropython.readthedocs.io/en/v2-docs/devguide/repl.html#using-a-serial-communication-program section, between the first and second paragraph would be good.
Would you like to create a PR to add it?

**Comment by rhubarbdog** [comment]
Yes I can do

**Comment by rhubarbdog** [comment]
i've completed the PR its https://github.com/bbcmicrobit/micropython/pull/785 if you want to check it's ok

**Comment by microbit-carlos** [comment]
PR https://github.com/bbcmicrobit/micropython/pull/785 was merged and this can be closed, thanks @rhubarbdog!
